name = "FastRefine"
uuid = "539d6ff6-d43f-40ec-ae8e-4530acef2765"
authors = ["Alex"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
